src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbr_pers;


    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_r;

    /**
     * @ORM\ManyToOne(targetEntity=Evenement::class, inversedBy="reservations")
     */
    private $Evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbrPers(): ?int
    {
        return $this->nbr_pers;
    }

    public function setNbrPers(int $nbr_pers): self
    {
        $this->nbr_pers = $nbr_pers;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDateR(): ?\DateTime
    {
        return $this->date_r;
    }

    public function setDateR(\DateTime $date_r): self
    {
        $this->date_r = $date_r;

        return $this;
    }

    public function getEvenement(): ?Evenement
    {
        return $this->Evenement;
    }

    public function setEvenement(?Evenement $Evenement): self
    {
        $this->Evenement = $Evenement;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nbr_pers')
            ->add('date')
            ->add('date_r', DateTimeType::class,['data'   => new \DateTime(),
                'attr'   => ['min' => ( new \DateTime() )->format('Y-m-d H:i:s')]])
            ->add('evenement', EntityType::class,
            [
                    'class' => Evenement::class,
                    'choice_label' => 'nom'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;

/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{

    /**
     * @Route("/email",name="sendemail")
     */
    public function sendEmail(MailerInterface $mailer)
    {
        $email = (new Email())
            ->from('chouchanecyrine@gmail.com')
            ->to('cyrine.chouchane@esprit.tn')
            //->cc('cc@example.com')
            //->bcc('bcc@example.com')
            //->replyTo('fabien@example.com')
            //->priority(Email::PRIORITY_HIGH)
            ->subject('Votre Réservation')
            ->text('Votre Réservation a été prise en compte')
            ->html('<p>Votre Réservation a été prise en compte</p>');
        //->attachFromPath('/path/to/documents/pdf.pdf');
        $mailer->send($email);
        return new Response(
            'Email was sent'
        );


    }

    /**
     * @Route("/list/{id}",name="list")
     */
    public function list($id)
    {
        $reservation = $this->getDoctrine()->getRepository(Reservation::class)->findAll();
        $Events = $this->getDoctrine()->getRepository(Evenement::class)->findAll();



        return $this->render('reservation/index.html.twig',
            [
                'reservations'=>$reservation,
                'Event' => $Events,
            ]);
    }

    /**
     * @Route("/tri/date", name="tri_date")
     * @param Request $request
     * @param $reservation
     * @return Response
     */
    public function TriActionDate(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery(
            'SELECT r FROM App\Entity\Reservation r
    ORDER BY r.date ASC');



        $reservation = $query->getResult();

        return $this->render('reservation/index.html.twig', array(
            'reservations' => $reservation));

    }


    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),

        ]);
    }

    /**
     * @Route("/pdf", name="pdf", methods={"GET"})
     */
    public function pdf(ReservationRepository $reservationRepository)
    {
        $Reservations = $reservationRepository->findAll();
        // Configure Dompdf according to your need
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('Reservation/mypdf.html.twig', ['Reservations' => $Reservations]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);
    }

    /**
     * @Route("/pdf2/{id}", name="pdf2", methods={"GET"})
     */
    public function pdf2(Reservation $reservation)
    {
        // Configure Dompdf according to your need
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('Reservation/mypdf2.html.twig', ['reservation' => $reservation]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf2.pdf", [
            "Attachment" => true
        ]);
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, MailerInterface $mailer): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($reservation);
            $entityManager->flush();
            $this->sendEmail($mailer);

            return $this->redirectToRoute('reservationdone', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/yes", name="reservationdone")
     */
    public function done(): Response
    {
        return $this->render('reservation/yes.html.twig');
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"POST"})
     */
    public function delete(Request $request, Reservation $reservation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}

{{ form_errors(form.date) }}
{{ form_label(form.date,"date d'arrivée") }}
{{ form_widget(form.date) }}

{{ form_errors(form.date_r) }}
{{ form_label(form.date_r,"date de retour") }}
{{ form_widget(form.date_r)}}


{{ form_errors(form.nbr_pers) }}
{{ form_label(form.nbr_pers,"Nombre de personnes") }}
{{ form_widget(form.nbr_pers)}}

{{ form_errors(form.evenement) }}
{{ form_label(form.evenement,"Choisir un evenement") }}
{{ form_widget(form.evenement)}}

<button class="btn">{{ button_label|default('je confirme ma réservation') }}</button>

{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/formreservation.html.twig
{% extends 'list.html.twig' %}



{% block body %}



    <div class="app-content">

    <div class="side-app">

    <div class="row">
    <div class="col-md-12">
        <div class="card m-b-20">
            <div class="card-header">
                <h3 class="card-title">Réserver une maison d'hote</h3>

            </div>
            {{ form_start(form)}}
            <div class="card-body">

                <form>
                    <div class="form-group">
                        <label class="form-label" for="exampleInputname">Date d'entrée</label>
                        {{ form_widget(form.dateentre ) }}
                        {{ form_errors(form.dateentre) }}
                    </div>


                    <div class="form-group">
                        <label class="form-label" for="exampleInputname">Date de sortie</label>
                        {{ form_widget(form.datesortie ) }}
                        {{ form_errors(form.datesortie) }}
                    </div>



                    <div class="form-group mb-0">

                        <div class="checkbox checkbox-secondary">
                            {{ form_widget(form) }}
                            <script src="https://js.stripe.com/v3/"></script>
                            <button id="checkout-button" type="submit" class="btn btn-success "  ><i class="fe fe-check mr-2"></i>Réserver</button>
                            <button id="checkout-button" type="submit" class="btn btn-success" href="{{ path('listmaisonhote') }}"><i class="fe fe-check mr-2"></i>Retour liste</button>



                        </div>
                    </div>
                    {% for message in app.flashes('success') %}
                        <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <i class="fa fa-check-circle-o mr-2" aria-hidden="true"></i>{{ message }}
                        </div>
                    {% endfor %}
                </form>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        // Create an instance of the Stripe object with your publishable API key
        var stripe = Stripe('pk_test_TYooMQauvdEDq54NiTphI7jx');
        var checkoutButton = document.getElementById('checkout-button');
        checkoutButton.addEventListener('click', function() {
            // Create a new Checkout Session using the server-side endpoint you
            // created in step 3.
            fetch('/create-checkout-session', {
                method: 'POST',
            })
                .then(function(response) {
                    return response.json();
                })
                .then(function(session) {
                    return stripe.redirectToCheckout({ sessionId: session.id });
                })
                .then(function(result) {
                    // If `redirectToCheckout` fails due to a browser or network
                    // error, you should display the localized error message to your
                    // customer using `error.message`.
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function(error) {
                    console.error('Error:', error);
                });
        });
    </script>




{%  endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ReservationController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/MSI/Desktop/Pi/src/Controller/ReservationController.php'|file_link(0) }}">src/Controller/ReservationController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/MSI/Desktop/Pi/templates/reservation/index.html.twig'|file_link(0) }}">templates/reservation/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/reservation/list.html.twig
{% extends 'base.html.twig' %}


{% block content %}
    <h1 align="center">Liste des reservations</h1>

    <table class="table">
        <thead>
        <tr>
            <th> id </th>
            <th>Nombre de personnes</th>
            <th>Date d'arrivée</th>
            <th>Date de retour</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.nbrPers }}</td>
                <td>{{ reservation.date ? reservation.date.format('year(s), month(s), day(s)')  }}</td>
                <td>{{ reservation.dateR ? reservation.dateR.format('year(s), month(s), day(s)')  }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/listre.html.twig
{% extends 'back.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}

{% endblock %}

templates/reservation/mypdf.html.twig
<html>
<head>
    <meta charset="UTF-8">
    <title>Liste des Reservations</title>
</head>
<body>
<table id="customers">
    <thead>
    <tr>
        <th> id </th>
        <th>Nombre de personnes</th>
        <th>Date d'arrivée</th>
        <th>Date de retour</th>
    </tr>
    </thead>
    <tbody>
    {% for reservation in Reservations %}
        <tr>
            <td>{{ reservation.id }}</td>
            <td>{{ reservation.nbrPers }}</td>
            <td>{{ reservation.date ? reservation.date|date('d-m-Y') : '' }}</td>
            <td>{{ reservation.dateR ? reservation.dateR|date('d-m-Y') : '' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>
<style>
    #customers {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #customers td, #customers th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    #customers tr:nth-child(even){background-color: #f2f2f2;}

    #customers tr:hover {background-color: #ddd;}

    #customers th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
    }

</style>

templates/reservation/mypdf2.html.twig
<html>
<head>
    <meta charset="UTF-8">
    <title>Liste des Reservations</title>
</head>
<body>
<table id="customers">
    <thead>
    <tr>
        <th> id </th>
        <th>Nombre de personnes</th>
        <th>Date d'arrivée</th>
        <th>Date de retour</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ reservation.id }}</td>
            <td>{{ reservation.nbrPers }}</td>
            <td>{{ reservation.date ? reservation.date|date('d-m-Y') : '' }}</td>
            <td>{{ reservation.dateR ? reservation.dateR|date('d-m-Y') : '' }}</td>
        </tr>
    </tbody>
</table>
</body>
</html>
<style>
    #customers {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #customers td, #customers th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    #customers tr:nth-child(even){background-color: #f2f2f2;}

    #customers tr:hover {background-color: #ddd;}

    #customers th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
    }

</style>

templates/reservation/new.html.twig
{% extends 'welcomeee.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}

    <h2 class="destination__title">Veuillez Remplir le Formulaire de Réservation</h2>


    {{ include('reservation/_form.html.twig') }}

    <form style="margin-left: 550px" action="{{ path('calendrier', {'id': 1})  }}">
        <button class="place__title">Calendrier de reservations</button>
    </form>

{% endblock %}

templates/reservation/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Voici le nombre de personnes</th>
                <td>{{ reservation.nbrPers }}</td>
            </tr>
            <tr>
                <th>Date d'arrivée</th>
                <td>{{ reservation.date ? reservation.date|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Date de retour</th>
                <td>{{ reservation.dateR ? reservation.dateR|date('d-m-Y') : '' }}</td>

            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>
    <a href="{{ path('pdf2', {'id': reservation.id}) }}">télécharger pdf</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/yes.html.twig
{% extends 'welcomeee.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}

{% endblock %}