src/Entity/Promo.php
<?php

namespace App\Entity;

use App\Repository\PromoRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;


/**
 * @ORM\Entity(repositoryClass=PromoRepository::class)
 */
class Promo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")

     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Groups("post:read")

     */
    private $Nom_promo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")
     *
     */
    private $nv_prix;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("post:read")

     */
    private $Description_promo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPromo(): ?string
    {
        return $this->Nom_promo;
    }

    public function setNomPromo(string $Nom_promo): self
    {
        $this->Nom_promo = $Nom_promo;

        return $this;
    }

    public function getNvPrix(): ?string
    {
        return $this->nv_prix;
    }

    public function setNvPrix(string $nv_prix): self
    {
        $this->nv_prix = $nv_prix;

        return $this;
    }

    public function getDescriptionPromo(): ?string
    {
        return $this->Description_promo;
    }

    public function setDescriptionPromo(string $Description_promo): self
    {
        $this->Description_promo = $Description_promo;

        return $this;
    }
}

src/Form/PromoType.php
<?php

namespace App\Form;

use App\Entity\Promo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;


class PromoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom_promo')
            ->add('nv_prix')
            ->add('Description_promo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promo::class,
        ]);
    }
}

src/Controller/PromoController.php
<?php

namespace App\Controller;

use App\Entity\Promo;
use App\Form\PromoType;
use App\Repository\PromoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/promo")
 */
class PromoController extends AbstractController
{
    /**
     * @Route("/indexfront", name="app_promo_indexfront", methods={"GET"})
     */
    public function index(PromoRepository $promoRepository): Response
    {
        return $this->render('promo/indexfront.html.twig', [
            'promos' => $promoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/indexback", name="app_promo_indexback", methods={"GET"})
     */
    public function indexback(PromoRepository $promoRepository): Response
    {
        return $this->render('promo/indexback.html.twig', [
            'promos' => $promoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_promo_new", methods={"GET", "POST"})
     */
    public function new(Request $request, PromoRepository $promoRepository, \Swift_Mailer $Mailer): Response
    {
        $promo = new Promo();
        $form = $this->createForm(PromoType::class, $promo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promoRepository->add($promo);
            $message= (new Swift_Message('nouveau Promo'))
                // on attribut l'epéditeur
                ->setFrom('ihebbt@gmail.com')
                //on attribut le destinataire
                ->setTo('ihebbt@gmail.com')
                // on crée le message la vue Twig
                ->setBody($this->renderView(
                    'emails/Promo.html.twig'
                ), 'text/html'


                );

            ; //on envoie le message
            $Mailer->send($message);
            return $this->redirectToRoute('app_promo_indexback', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promo/new.html.twig', [
            'promo' => $promo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_promo_show", methods={"GET"})
     */
    public function show(Promo $promo): Response
    {
        return $this->render('promo/show.html.twig', [
            'promo' => $promo,
        ]);
    }

    /**
     * @Route("/showfront/{id}", name="app_promo_showfront", methods={"GET"})
     */
    public function showfront(Promo $promo): Response
    {
        return $this->render('promo/showfront.html.twig', [
            'promo' => $promo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_promo_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Promo $promo, PromoRepository $promoRepository): Response
    {
        $form = $this->createForm(PromoType::class, $promo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promoRepository->add($promo);
            return $this->redirectToRoute('app_promo_indexback', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promo/edit.html.twig', [
            'promo' => $promo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_promo_delete", methods={"GET","POST"})
     */
    public function delete(Request $request, Promo $promo, PromoRepository $promoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promo->getId(), $request->request->get('_token'))) {
            $promoRepository->remove($promo);
        }

        return $this->redirectToRoute('app_promo_indexback', [], Response::HTTP_SEE_OTHER);
    }
}

templates/promo/_delete_form.html.twig
<form method="post" action="{{ path('app_promo_delete', {'id': promo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promo/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Edit Promo{% endblock %}

{% block body %}
    <h1>Edit Promo</h1>

    {{ include('promo/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_promo_indexback') }}">back to list</a>

    {{ include('promo/_delete_form.html.twig') }}
{% endblock %}

templates/promo/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Promo index{% endblock %}

{% block body %}
    <h1>Promo index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_promo</th>
                <th>Nv_prix</th>
                <th>Description_promo</th>
                
            </tr>
        </thead>
        <tbody>
        {% for promo in promos %}
            <tr>
                <td>{{ promo.id }}</td>
                <td>{{ promo.NomPromo }}</td>
                <td>{{ promo.nvPrix }}</td>
                <td>{{ promo.DescriptionPromo }}</td>
                <td>
                    <a href="{{ path('app_promo_showfront', {'id': promo.id}) }}">show</a>
                    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

  
{% endblock %}

templates/promo/indexback.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Promo index{% endblock %}

{% block body %}
    <h1>Promo index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_promo</th>
                <th>Nv_prix</th>
                <th>Description_promo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promo in promos %}
            <tr>
                <td>{{ promo.id }}</td>
                <td>{{ promo.NomPromo }}</td>
                <td>{{ promo.nvPrix }}</td>
                <td>{{ promo.DescriptionPromo }}</td>
                <td>
                    <a href="{{ path('app_promo_show', {'id': promo.id}) }}">show</a>
                    <a href="{{ path('app_promo_edit', {'id': promo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_promo_new') }}">Create new</a>
{% endblock %}

templates/promo/indexfront.html.twig
{% extends 'frontcentre.html.twig' %}

{% block title %}Promo index{% endblock %}

{% block body %}
    <h1>Promo index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_promo</th>
                <th>Nv_prix</th>
                <th>Description_promo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promo in promos %}
            <tr>
                <td>{{ promo.id }}</td>
                <td>{{ promo.NomPromo }}</td>
                <td>{{ promo.nvPrix }}</td>
                <td>{{ promo.DescriptionPromo }}</td>
                <td>
                    <a href="{{ path('app_promo_showfront', {'id': promo.id}) }}">show</a>
                   
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   
{% endblock %}

templates/promo/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}New Promo{% endblock %}

{% block body %}
    <h1>Create new Promo</h1>

    {{ include('promo/_form.html.twig') }}

    <a href="{{ path('app_promo_indexback') }}">back to list</a>
{% endblock %}

templates/promo/show.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Promo{% endblock %}

{% block body %}
    <h1>Promo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promo.id }}</td>
            </tr>
            <tr>
                <th>Nom_promo</th>
                <td>{{ promo.NomPromo }}</td>
            </tr>
            <tr>
                <th>Nv_prix</th>
                <td>{{ promo.nvPrix }}</td>
            </tr>
            <tr>
                <th>Description_promo</th>
                <td>{{ promo.DescriptionPromo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_promo_indexback') }}">back to list</a>

    <a href="{{ path('app_promo_edit', {'id': promo.id}) }}">edit</a>

    {{ include('promo/_delete_form.html.twig') }}
{% endblock %}

templates/promo/showfront.html.twig
{% extends 'frontcentre.html.twig' %}

{% block title %}Promo{% endblock %}

{% block body %}
    <h1>Promo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promo.id }}</td>
            </tr>
            <tr>
                <th>Nom_promo</th>
                <td>{{ promo.NomPromo }}</td>
            </tr>
            <tr>
                <th>Nv_prix</th>
                <td>{{ promo.nvPrix }}</td>
            </tr>
            <tr>
                <th>Description_promo</th>
                <td>{{ promo.DescriptionPromo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_promo_indexfront') }}">back to list</a>

   

    {{ include('promo/_delete_form.html.twig') }}
{% endblock %}